name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Vulkan SDK
      shell: powershell
      run: |
        # Download and install Vulkan SDK
        $url = "https://sdk.lunarg.com/sdk/download/1.4.321.1/windows/vulkansdk-windows-X64-1.4.321.1.exe"
        $output = "$env:TEMP\VulkanSDK.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList "--root", "C:\VulkanSDK\1.4.321.1", "--accept-licenses", "--default-answer", "--confirm-command", "install" -Wait -NoNewWindow -Verb RunAs

        # Add Vulkan to PATH
        $vulkanPath = "C:\VulkanSDK\1.4.321.1\Bin"
        echo "$vulkanPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup vcpkg
      shell: powershell
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        echo "VCPKG_ROOT=$((Get-Location).Path)\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install dependencies
      shell: powershell
      run: |
        .\vcpkg\vcpkg.exe install glfw3:x64-windows
        .\vcpkg\vcpkg.exe install glm:x64-windows

    - name: Configure CMake
      shell: powershell
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      shell: powershell
      run: |
        cmake --build build --config Release

    - name: List build output
      shell: powershell
      run: |
        Get-ChildItem -Recurse build/Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-app-windows
        path: |
          build/Release/*.exe
          build/Release/*.spv
          build/Release/*.dll
        retention-days: 7