name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.4.321.1
        destination: C:\VulkanSDK\1.4.321.1
        optional_components: "core"

    - name: Setup vcpkg and install dependencies
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitURL: 'https://github.com/Microsoft/vcpkg.git'
        vcpkgGitCommitId: 'a923876489993098f7b53608377424175227912d'
        runVcpkgInstall: true
        vcpkgTriplet: 'x64-windows'
        additionalVcpkgInstallArgs: 'glfw3 glm'

    - name: Configure CMake
      shell: powershell
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      shell: powershell
      run: |
        cmake --build build --config Release

    - name: List build output
      shell: powershell
      run: |
        Get-ChildItem -Recurse build/Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-app-windows
        path: |
          build/Release/*.exe
          build/Release/*.spv
          build/Release/*.dll
        retention-days: 7